---
# Change this if you plan on having multiple separate instances of ScoreStack
# running at the same time in your environment.
cluster.name: scorestack

network.host: 0.0.0.0

xpack.monitoring.enabled: true
xpack.monitoring.collection.enabled: true

xpack.security.enabled: true

xpack.security.authc.realms.native.native1.order: 0

xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.client_authentication: none
xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certificates/elasticsearch/elasticsearch.key
xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certificates/elasticsearch/elasticsearch.crt
xpack.security.http.ssl.certificate_authorities:
  - /usr/share/elasticsearch/config/certificates/ca/ca.crt

xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.verification_mode: full
xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certificates/elasticsearch/elasticsearch.key
xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certificates/elasticsearch/elasticsearch.crt
xpack.security.transport.ssl.certificate_authorities:
  - /usr/share/elasticsearch/config/certificates/ca/ca.crt