---
csp.strict: true

elasticsearch.ssl.certificate: /usr/share/kibana/config/certificates/kibana/kibana.crt
elasticsearch.ssl.key: /usr/share/kibana/config/certificates/kibana/kibana.key
elasticsearch.ssl.certificateAuthorities:
  - /usr/share/kibana/config/certificates/ca/ca.crt

elasticsearch.username: kibana

path.data: /usr/share/kibana/data

server.host: "0.0.0.0"

server.ssl.certificate: /usr/share/kibana/config/certificates/kibana/kibana.crt
server.ssl.key: /usr/share/kibana/config/certificates/kibana/kibana.key
server.ssl.certificateAuthorities:
  - /usr/share/kibana/config/certificates/ca/ca.crt
server.ssl.enabled: true

uiSettings.overrides.theme.darkMode: true