---
cluster.name: scorestack
node.name: elasticsearch
network.host: "0.0.0.0"
bootstrap.memory_lock: true
discovery.type: single-node

xpack.security.enabled: true

xpack.security.http.ssl.enabled: true
xpack.security.http.ssl.key: certs/elasticsearch/elasticsearch.key
xpack.security.http.ssl.certificate: certs/elasticsearch/elasticsearch.crt
xpack.security.http.ssl.certificate_authorities:
  - certs/ca/ca.crt
xpack.security.http.ssl.verification_mode: certificate

xpack.security.transport.ssl.enabled: true
xpack.security.transport.ssl.key: certs/elasticsearch/elasticsearch.key
xpack.security.transport.ssl.certificate: certs/elasticsearch/elasticsearch.crt
xpack.security.transport.ssl.certificate_authorities:
  - certs/ca/ca.crt
xpack.security.transport.ssl.verification_mode: certificate